base_images:
  base:
    name: ubi
    namespace: ocp
    tag: "8"
  cli:
    name: "4.13"
    namespace: origin
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- dockerfile_literal: |
    FROM registry.ci.openshift.org/origin/4.13:cli

    RUN wget -q https://github.com/openshift-online/ocm-cli/releases/download/v0.1.66/ocm-linux-amd64 -O /usr/local/bin/ocm &&\
        chmod +x /usr/local/bin/ocm &&\
        ocm version

    RUN curl -s https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo -o /etc/yum.repos.d/hashicorp.repo &&\
        yum install -y terraform &&\
        terraform version

    RUN yum -y install --setopt=skip_missing_names_on_install=False \
        openssl jq unzip which
    RUN yum clean all

    RUN git config --global http.sslVerify false &&\
        git clone https://github.com/AsherShoshan/terraform-provider-ocm.git --branch main --depth=1
  to: ocm-tf-cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.13"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: terraform-rehearse-debug
  cron: '@yearly'
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
    workflow: rosa-aws-terraform
zz_generated_metadata:
  branch: master
  org: openshift
  repo: rosa
