base_images:
  base:
    name: ubi
    namespace: ocp
    tag: "8"
  cli:
    name: "4.12"
    namespace: origin
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.19
images:
- dockerfile_literal: |
    FROM registry.ci.openshift.org/origin/4.12:cli

    RUN wget -q https://github.com/openshift-online/ocm-cli/releases/download/v0.1.66/ocm-linux-amd64 -O /usr/local/bin/ocm &&\
        chmod +x /usr/local/bin/ocm &&\
        ocm version

    RUN curl -s https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo -o /etc/yum.repos.d/hashicorp.repo &&\
        yum install -y terraform &&\
        terraform version

    RUN yum -y install --setopt=skip_missing_names_on_install=False \
        openssl jq unzip which make
    RUN yum clean all

    RUN git config --global http.sslVerify false &&\
        git clone https://github.com/terraform-redhat/terraform-provider-ocm.git --branch main

    RUN curl -Ls https://go.dev/dl/go1.20.4.linux-amd64.tar.gz |tar -C /usr/local -xzf -

    ENV PATH="/usr/local/go/bin:${PATH}"
    ENV GOPATH=/usr/local/go
    RUN cd terraform-provider-ocm && go mod tidy && go mod vendor && make install
  to: ocm-tf-cli
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: terraform-rehearse-debug
  cron: '@yearly'
  steps:
    cluster_profile: aws-qe
    workflow: rosa-aws-terraform
- as: terraform-rehearse-e2e
  cron: '@yearly'
  steps:
    cluster_profile: aws-qe
    workflow: rosa-aws-terraform
zz_generated_metadata:
  branch: master
  org: openshift
  repo: rosa
